services:
  - type: web
    name: scoreboard
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: Scoreboard-backend/Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CORS_ORIGINS
        value: ""
